services:
  client:
    build:
      context: ./client
    container_name: cinebook-client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src

  server:
    build:
      context: ./server
    container_name: cinebook-server
    restart: always
    ports:
      - "8000:80"
    environment:
      APP_NAME: CineBook
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      FRONTEND_URL: http://localhost:5173
      DB_CONNECTION: sqlsrv
      DB_HOST: db
      DB_PORT: 1433
      DB_DATABASE: cinebook_db
      DB_USERNAME: sa
      DB_PASSWORD: "CineBook@1234"
      DB_TRUST_SERVER_CERTIFICATE: "true"
    depends_on:
      - db
      - db-init

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cinebook_db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "CineBook@1234"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - cinebook_db_data:/var/opt/mssql

  db-init:
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: cinebook_db_init
    depends_on:
      - db
    volumes:
      - ./database/migrations:/sql
      - ./database/init/entrypoint.sh:/entrypoint.sh
    command: /bin/bash /entrypoint.sh

volumes:
  cinebook_db_data: