version: "3.9"

services:
  client:
    build:
      context: ./client
    container_name: cinebook-client
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src

