version: "3.9"

services:
  client:
    build:
      context: ./client
      args:
        VITE_BACKEND_ENDPOINT: http://server:5000
    #container_name: cinebook_client
    restart: always
    ports:
      - "3000:80"
    #depends_on:
      #- server

